### ISSUE TITLE
Remove links to registration

### ISSUE THREAD

**Issue by Auraelius** [pianopushplay/admin_ui#23]
Since this is an invitation-only app, admin users are currently added directly to the database and volunteer users are added by admins. There is no registration process.
Route: http://127.0.0.1:5000/admin/login/

Remove the "Not yet signed up? Please register for an account." link on the login form.

![screen shot 2017-10-27 at 3 22 27 pm](https://user-images.githubusercontent.com/47005/32127709-97aaa492-bb2d-11e7-9f5e-649ed7bea0e0.png)

Also remove the Register button from the admin screen

![screen shot 2017-10-27 at 3 53 02 pm](https://user-images.githubusercontent.com/47005/32127923-01777f84-bb2f-11e7-995b-c5fcacea1144.png)

**Comment by Adrianacmy** [comment]
I simply remove the register
